homeassistant: !include home.yaml

# Configure a default setup of Home Assistant (frontend, api, etc)

default_config:

# config:

frontend:

  themes: !include_dir_merge_named themes/

  extra_html_url:

    - /local/hass-fontawesome-solid.html

    - /local/hass-fontawesome-regular.html

    - /local/hass-fontawesome-brands.html

lovelace:

  mode: yaml

duckdns:

  domain: tzjbe

  access_token: !secret domain_token

http:

  base_url: !secret url

  ssl_certificate: !secret cert

  ssl_key: !secret key

# Select theme

input_select:

  hass_theme:

    name: HASS Themes

    options:

      - default

      - BlueNight

      - midnight

      - teal

      - DarkBlue

    initial: default

    icon: far:align-left

weather:

  - platform: darksky

    api_key: !secret weather_token

    name: Vremea

    # monitored_conditions:

    #   - summary
    
    #   - icon

    #   - temperature

# Text to speech

tts:

  - platform: google_translate

    cache: true

    cache_dir: /tmp/tts

    time_memory: 300

    base_url: https://192.168.0.64:8123

    service_name: google_say

fan:

  - platform: xiaomi_miio

    host: !secret fan_host

    token: !secret fan_token

switch:

    - platform: mqtt

      name: "Switch1"

      state_topic: "ha/switch1"

      command_topic: "ha/switch1"

      qos: 0

      payload_on: "ON"

      payload_off: "OFF"

      # optimistic:

      # false retain: true

    - platform: mqtt

      name: "Switch2"

      state_topic: "switch2"

      command_topic: "switch2"

      qos: 0

      payload_on: "ON"

      payload_off: "OFF"

      # optimistic:

      # false retain: true

xiaomi_aqara:

  discovery_retry: 5

  gateways:

    - key: !secret miio_gateway_key

# vacuum:

#   - platform: xiaomi_miio

#     host: !secret vacuum_host

#     token: !secret vacuum_token

# ios:

# for iphone/ipad or other autodiscover devices

discovery:

ios:
  push:
    categories:
      - name: movement
        identifier: movement
        actions:
          - identifier: MOVEMENT
            title: "Turn Lights Off"
            activationMode: 'background'
            authenticationRequired: no
            destructive: yes
            behavior: 'default'

zeroconf:

# notify:

# mobile_app:

map:

# TVs Media config

media_player:

  - platform: webostv

    host: !secret webostv_host

    name: Bedroom TV

    filename: webostv.conf

    timeout: 5

    turn_on_action:
      service: persistent_notification.create
      data:
        message: "Turn on action"

    customize:

      sources:

        - livetv

        - youtube

        - makotv

        - netflix
  
  - platform: lg_netcast

    name: Living Room TV

    host: !secret lg_livingroom_tv_host

    access_token: !secret lg_livingroom_tv_token

  # - platform: dlna_dmr
  #   url: http://192.168.0.64:8200/rootDesc.xml

# GOOGLE ASSISTANT

google_assistant:

  project_id: !secret google_project_id

  api_key: !secret google_api

  exposed_domains:

    - media_player

    - sensor

    - light.gateway_light_7c49ebb190e9

  entity_config:

    media_player.webos:

      name: LG_TV

mqtt:

  broker: !secret mqtt_host

  password: !secret mqtt_pass

person: !include persons.yaml

sensor: !include sensors.yaml

group: !include groups.yaml

automation: !include automations.yaml

script: !include scripts.yaml

hacs:

  token: !secret hacs_tocken

spotcast:

  username: !secret spotify_username

  password: !secret spotify_password

plex:
  host: 192.168.0.64
  port: 32400
  # token: claim-j_wp17qgNyZF8yjzsaWP

# logger:
#   default: info
  # logs:
  #   homeassistant.core: debug
  #   # nest.nest: debug
  #   asyncio: debug
  #   homeassistant.components.cloud.iot: debug